from enum import Enum

class State(Enum):
    IDLE_NOCARD = "I_NOCARD"
    IDLE_UNAUTHORIZED = "I_UNAUTHORIZED"
    IDLE_AUTH_WAITINGPIN = "I_WAITINGPIN"
    RUNNING_AUTHORIZED = "R_AUTHORIZED"
    RUNNING_NOCARD = "R_NOCARD"
    RUNNING_PROXY = "R_PROXY"
    RUNNING_TRAINING= "R_TRAINING"
