class State():
    IDLE_NOCARD = "I_NOCARD"
    IDLE_UNAUTHORIZED = "I_UNAUTHORIZED"
    IDLE_AWAIT_PIN = "I_AWAIT_PIN"
    RUNNING_AUTHORIZED = "R_AUTHORIZED"
    RUNNING_NOCARD = "R_NOCARD"
    RUNNING_PROXY = "R_PROXY"
    RUNNING_TRAINING= "R_TRAINING"
